FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.15

# set version label
ARG BUILD_DATE
ARG VERSION
ARG FLEET_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="Josh Stark,Thelamer"

# copy files
COPY root/ /
