#!/usr/bin/with-contenv bash

if [[ "$(uname -m)" == "armv7l" ]]; then
    sleep infinity
fi

exec \
    s6-setuidgid abc /usr/bin/java -Dfleet.config.base=/config -Dlog4j2.formatMsgNoLookups=true -jar /app/fleet/fleet.jar
