# Based on the issue template
name: Feature request
description: Suggest an idea for this project
title: "[FEAT] <title>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
# DEPRECATION NOTICE 
This image is deprecated. We will not offer support for this image and it will not be updated.


We deprecated our Fleet container and Fleet application due to issues maintaining the necessary level of development
